### Site info:
title: Yinqi Huang' blog
tagline: Have a big dream!
author: Yinqi Huang
email: hyq9508@gmail.com
description: "Have a big dream!" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "web html css js jquery"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hyq9508.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
github_username:  hyq9508
disqus_shortname: hyq
favicon:     "images/favicon.ico"
aboutme: 一个没事儿就喜欢出去旅游出去浪的程序媛 # these are shown on aboutme-sidebar.
aboutme_photo: images/aboutme.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (weibo,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "



### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
